### ISSUE TITLE
Bot verification

### ISSUE THREAD

**Issue by lightlybakedman** [apollyon600/ProjectAlpha#1]
The bot is unable to join servers as it is unverified

![Screenshot_2020-10-11-10-41-15-976_com android chrome](https://user-images.githubusercontent.com/57511929/95667195-57315d00-0bae-11eb-9f31-016ec8c1085a.jpg)

**Comment by patrickjonesuk** [comment]
This is not due to lack of verification, the bot is verified. This is most likely due to certain privileged gateway intents being enabled but not being whitelisted for them. This issue can be temporarily resolved but disabling the intents from the developer console. This will allow the bot to be added to servers while awaiting response from discord's support team to be whitelisted. Apply at dis.gd/contact

**Comment by johnaqu1no** [comment]
This was resolved after closing both gateways since they are unnecessary, thank you for reporting this!
